# .github/workflows/pr-push.yml
name: Publish Working Draft
on:
  pull_request: {}
  push:
    branches: [main]
    paths: ['index.html']
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN }}
          W3C_WG_DECISION_URL: https://www.w3.org/2024/09/24-did-minutes.html#r02
          W3C_BUILD_OVERRIDE: |
             shortName: did-1.1
             specStatus: WD
